### PR TITLE
fix(build): set correct codesigning target

### LINKED ISSUE #18: "No target "OUTPUT_NAME"" when building on MacOS
When attempting to build on MacOS 14.4 on apple silicon, I get the following error while running cmake:

```
-- Configuring done (32.1s)
CMake Error at Source/Core/DolphinQt/CMakeLists.txt:681 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_BUNDLE_DIR:OUTPUT_NAME>

  No target "OUTPUT_NAME"


CMake Error at Source/Core/DolphinQt/CMakeLists.txt:681 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_BUNDLE_DIR:OUTPUT_NAME>

  No target "OUTPUT_NAME"


CMake Error at Source/Core/DolphinQt/CMakeLists.txt:681 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_BUNDLE_DIR:OUTPUT_NAME>

  No target "OUTPUT_NAME"


-- Generating done (1.4s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

It looks like you attempted to replace dolphin-emu with `OUTPUT_NAME`, but it's not defined at that point in the script.

### PR DESCRIPTION
**Pull request by vladfi1**
A couple changes needed to get the `build-mac.sh` script working on my M1 machine.

The xxhash thing is unsatisfying but oh well.

### CODE REVIEW

File: build-mac.sh [hunk 1]
```diff
@@ -4,6 +4,11 @@
 QT_BREW_PATH=$(brew --prefix qt@6)
 CMAKE_FLAGS="-DQT_DIR=${QT_BREW_PATH}/lib/cmake/Qt6 -DENABLE_NOGUI=false"
 
+# For some reason the system xxhash library doesn't get properly linked,
+# at least on my M1. The clang command gets -lxxhash, but probably needs
+# -L/opt/homebrew/Cellar/xxhash/... to actually find the library.
+CMAKE_FLAGS+=" -DUSE_SYSTEM_XXHASH=OFF"
```
Comment (NikhilNarayana) [inline build-mac.sh]:
```suggestion
if [[ $(arch) == 'arm64' ]]; then
  CMAKE_FLAGS+=" -DUSE_SYSTEM_XXHASH=OFF"
fi
```
please gate this behind an arm64 check like above. i see no reason to change what our CI does at this time

**Review by NikhilNarayana — CHANGES_REQUESTED** [review]

File: build-mac.sh (hunk 1 above)
Comment (vladfi1) [reply build-mac.sh]: done

**Review by NikhilNarayana — APPROVED** [review]
